services:
  recurring-payments-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: recurring_payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
