jwt:
  secret: superSekretnyKluczJWT123456789012345678901234567890
  expiration: 3600
spring:
  application:
    name: Recurring Payments API
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
  flyway:
    locations: classpath:db/migration
  threads:
    virtual:
      enabled: true

server:
  port: 8080
billing:
  charge-cron: "0 * * * * *"

outbox:
  publish-cron: "*/15 * * * * *"
  batch-size: 100

logging:
  level:
    root: ERROR
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings