jwt:
  secret: superSekretnyKluczJWT123456789012345678901234567890
  expiration: 3600
  refresh-expiration: 1209600

spring:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  application:
    name: Recurring Payments API
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
  flyway:
    locations: classpath:db/migration
  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8080

billing:
  charge-cron: "0 * * * * *"

outbox:
  publish-cron: "*/15 * * * * *"
  batch-size: 100

logging:
  level:
    root: ERROR
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings
